api_platform:
    title: 'API BILEMO'
    description: 'Get list of Mobile and manage Client'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
